- name: Installing webserver application
  hosts: localhost
  become: yes
  tasks:
  - name: Downloading webserver
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: remove default nginx page
    ansible.builtin.file:
      path: /user/share/nginx/html
      state: absent
  - name: creating new html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  - name: COPY CUSTOM nginx page
    ansible.builtin.copy:
      src: index.html
      dest: /usr/share/nginx/html
  - name: Starting webserver
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes